### ISSUE TITLE
Bug : setting the wrong concurrency number crashes the tool

### ISSUE THREAD

**Issue by HobbyProjects** [Joll59/d-ser-t#35]
Only 4 files and concurrency of 17 causes a crash. Please see below. Setting the concurrency to 2 resolved the problem.

>node lib\main.js -s xxxxxxxx -r westus2 -e yyyyyyyy -c 17 -d C:\SBUX\d-ser-t\audio -t "C:\SBUX\ramsay-utterances\transcripts\add-to-order-manual-text-utterances.txt"
Starting Recognizer 0 . . .
Starting Recognizer 1 . . .
Starting Recognizer 2 . . .
Starting Recognizer 3 . . .
#### ENCOUNTERED AN ERROR ####:
 TypeError: Cannot read property 'recording' of undefined
    at C:\SBUX\d-ser-t\lib\TranscriptionService.js:83:62
    at new Promise (<anonymous>)
    at TranscriptionService.internalRecognizer (C:\SBUX\d-ser-t\lib\TranscriptionService.js:56:20)
    at C:\SBUX\d-ser-t\lib\TranscriptionService.js:111:101
    at Array.map (<anonymous>)
    at TranscriptionService.batchTranscribe (C:\SBUX\d-ser-t\lib\TranscriptionService.js:111:45)
    at Object.exports.start (C:\SBUX\d-ser-t\lib\main.js:42:23)
    at Object.<anonymous> (C:\SBUX\d-ser-t\lib\main.js:74:13)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)

**Comment by Joll59** [comment]
Addressed by #51
